# Generated by Django 3.0.9 on 2020-08-24 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_remove_post_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Theme_board',
        ),
        migrations.DeleteModel(
            name='Theme_board',
        ),
    ]
